services:
  database:
    image: postgres:14.0
    container_name: firecode_db
    env_file: ./.env
    volumes:
      - firecode_db:/var/lib/postgresql/data/
    networks:
      - firecode
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./app/
    container_name: firecode_django
    env_file: ./.env
    volumes:
      - firecode_static:/usr/src/app/static/
    networks:
      - firecode
    working_dir: /usr/src/app/
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      database:
        condition: service_healthy
    restart: always

  nginx:
    build: ./nginx
    container_name: firecode_nginx
    volumes:
      - firecode_static:/usr/src/app/static/
    networks:
      - firecode
    ports:
      - '8088:80'
    depends_on:
      - web
    restart: always

networks:
  firecode:

volumes:
  firecode_db:
  firecode_static:
