# Generated by Django 3.2.8 on 2021-10-28 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20211028_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='название магазина')),
                ('building', models.CharField(max_length=10, verbose_name='номер дома')),
                ('opening_time', models.TimeField(verbose_name='время открытия')),
                ('closing_time', models.TimeField(verbose_name='время закрытия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to='shops.city', verbose_name='город')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to='shops.street', verbose_name='улица')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'street', 'building'), name='shop_city_street_building_unique'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(check=models.Q(('closing_time__gt', django.db.models.expressions.F('opening_time'))), name='closing_time_gt_opening_time'),
        ),
    ]
